import { League_Spartan } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Carousel from "@/components/ui/Carousel"; // Importa el componente Carousel

const leagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define el array de imágenes para el carrusel
const images = [
  "/donofrio.jpg", // Ruta relativa desde la carpeta public
  "/imagen.png"
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${leagueSpartan.variable} antialiased`}>
        <Header /> {/* Llamamos al componente Header aquí */}
        <main>
          <Carousel images={images} /> {/* Integra el carrusel aquí */}
          {children} {/* Contenido dinámico renderizado */}
        </main>
      </body>
    </html>
  );
}